### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by jsczzzk** [qinguoyi/yolo-windows#1]
请问这个能在ubuntu下测试自己的图片吗？可以展示一下航拍数据集的效果图吗？谢谢您：）

**Comment by qinguoyi** [comment]
模型可以直接在Ubuntu下进行测试，效果图稍后上传

**Comment by jsczzzk** [comment]
老哥你这个效果真棒，请问该如何测试自己的图片(分辨率很大)呢？不知道该执行哪一个文件进行测试- -

**Comment by qinguoyi** [comment]
如果你在windows下测试，直接运行该代码即可对高分辨率图像进行车辆检测；若在ubuntu下测试，需要修改源码，先对图像进行分割，单独检测后再融合位置信息；若不知道ubuntu下如何测试，可以先看下readme中最后的博客网址，里面有训练及测试详解，祝好。
